version: '3.3'
services:
  wordpress:
    build: .
    volumes:
      - './.data:/var/www/html/wp-content'
      - './wp-config.php:/var/www/html/wp-config.php'
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 80:80
    restart: always

  mysql:
    image: mysql:5.7
    volumes:
      - './.data/db:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
